 version: 2

 jobs:
   build:
     docker:
       - image: circleci/python:jessie-browsers
     steps:
       - checkout
       - run:
           name: Install dependencies
           command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
       - run:
           name: Update chromedriver
           command: |
              curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
              sudo dpkg -i google-chrome.deb
              sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
              rm google-chrome.deb
       - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
       - run:
           name: Run tests
           command: |
              . venv/bin/activate
              python3 runner.py --browser=chrome --report
       - store_artifacts:
          path: screenshots
       - store_artifacts:
          path: reports

 workflows:
   version: 2
   commit:
     jobs:
       - build
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
